name: Build
on: [pull_request, push]

jobs:
  Build:
    runs-on: ubuntu-24.04
    steps:
      - name: Setup SSH for Private Repository
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_REPO_SSH_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          
      - name: Clone Private Dependency
        run: git clone git@github.com:Qingha821/Resource-Syncronization.git
        
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
          
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
        working-directory: ./Resource-Syncronization
        
      - name: Build
        run: ./gradlew build
        working-directory: ./Resource-Syncronization
          
      - name: Capture Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build Artifacts
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar
          working-directory: ./Resource-Syncronization
            
      - name: Cleanup SSH Keys
        run: rm -f ~/.ssh/id_ed25519
